config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  resources :checkouts
  
  get 'pages/home'
  get 'messages/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :charges, only: [:new, :create]
  resources :line_items
  resources :carts
  resources :instruments
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  root 'instruments#index'

  post 'messages', to: 'messages#create'

  get '/search' => 'instruments#search', :as => 'search_page'


  
  #resources :contactings, only: [:index, :new, :create] 
 
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :line_items, dependent: :destroy

	def add_instrument(instrument)
    current_item = line_items.find_by(instrument_id: instrument.id)

    if current_item
      current_item.increment(:quantity)
    else
      current_item = line_items.build(instrument_id: instrument.id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

    def paypal_url(return_url)
      values = {
        :business => 'sb-jnftp14141474@business.example.com',
        :cmd => '_cart',
        :upload => 1,
        :return => return_url,
        :invoice => id
      }
      line_items.each_with_index do |instrument, index|
        values.merge!({
          "amount_#{index+1}" => instrument.total_price,
          "item_name_#{index+1}" => instrument.total_price,
          "item_number_#{index+1}" => instrument.id,
          "quantity_#{index+1}" => instrument.quantity
        })
      end
      "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  before_action :set_cart, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  def index
    @carts = Cart.all
  end

  def show
  end

  def new
    @cart = Cart.new
  end

  def edit
  end

  def create
    @cart = Cart.new(cart_params)
    if @cart.save
      redirect_to @cart, notice: "Cart was successfully created." 
    else
      render :new, status: :unprocessable_entity 
    end
  end

  def update
    if @cart.update(cart_params)
      redirect_to @cart, notice: "Cart was successfully updated." 
    else
      render :edit, status: :unprocessable_entity 
    end
  end

  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    redirect_to root_path, notice: "Cart was successfully destroyed." 
  end

  private
  
  def set_cart
    @cart = Cart.find(params[:id])
  end

  def cart_params
    params.fetch(:cart, {})
  end
  def invalid_cart
    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to root_path, notice: "That cart doesn't exist"
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= simple_form_for(@cart) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/carts/_payment.html.erb
<%# <% if !@instrument.persisted? %>
<section class="section">
  <h4 class="subtitle is-4">Payment</h4>

  <div class="notification is-light has-text-centered">
  	<i class="fa fa-credit-card"></i>
  	All Instrument Cost <strong>$300</strong> USD
  	<span class="blocl mb4"></span>
  </div>

  <div class="form-row">
  	<label for="card-element" class="label">
  		Enter credit or debit card
  	</label>

  	<div id="card-element" class="form-control">
  		<!-- stripe element inserted -->
  	</div>
    <!-- display error -->
    <div id="card-errors" role="alert"></div>
  </div>
  
  <% if current_user.stripe_id.present? %>
  <div class="last-card bg-light pa4 border-radius-3 mt4">
    <h5 class="is-6 title pt2">Previously used card</h5>
    <table class="table is-narrow bg-light is-fullwidth">
     <thead>
      <th>Card Brand</th>
      <th>Last 4 Digits </th>
      <th>Expiration Month</th>
      <th>Expiration Year</th>
    </thead>
    <tr>
      <td><%= current_user.card_brand %></td>
      <td><%= current_user.card_last4 %></td>
      <td><%= current_user.card_exp_month %></td>
      <td><%= current_user.card_exp_year %></td>
    </tr>
  </table>
</div>
<% end %>
</section>
<%#<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
    <tr>
      <td><%= link_to 'Show', cart %></td>
      <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
      <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<!--<%#<p id="notice"><%= notice %></p>

<%#<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%#<%= link_to 'Back', carts_path %> -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<div class="keep-shopping pv1 mt4 has-text-right">
  <%= link_to 'Keep Shopping', instruments_path, class: 'button is-warning' %>
</div>

<!-- <script src="https://js.stripe.com/v3/"></script> -->

<!-- <div class="container">
  <div class='row'>
    <form action="/charge" method="post" id="payment-form">
      <div class="form-row">
        <label for="card-element">
          Credit or debit card
        </label>
        <div id="card-element">
         A Stripe Element will be inserted here. -->
         <!--  < --><!-- /div> --> 

         <!-- Used to display Element errors. -->
   <!--      <div id="card-errors" role="alert"></div>
      </div>

      <button>Submit Payment</button>
    </form>
  </div> -->
  <!-- </div> --> 

<%#  <div class="buy-now pv1 mt4 has-text-right">
<%#    <%= link_to 'Buy Now', new_charge_path, class: 'button is-success' %>
<%#  </div>  #%>

<!--   <div>
  <%#  <%= render 'payment' %>
  </div>  -->

  <hr />
  <section class="section">
    <%= render(@cart.line_items) %>

    <div class="columns">
      <div class="column">
        <%= button_to 'Empty Cart', @cart, method: :delete, data: { confirm: "Are you sure? " }, class: "button is-danger" %> <br>
      </div>
      <div class="column total has-text-right">
        <h4 class="title is-4">
          <span class="f5 has-text-grey">Total:</span> <%= number_to_currency(@cart.total_price) %>
        </h4>
      </div>
    </div>
   
    <div class="buy-now pv1 mt4 has-text-right">
      <%= link_to 'Checkout', @cart.paypal_url(root_path), class: 'button is-info' %>
    </div> 
    <div class="buy-now pv1 mt4 has-text-right">
      <%= link_to 'Checkout', new_checkout_path, class: 'button is-warning' %>
    </div> 
  </section>


<!-- <script>
var stripe = Stripe('pk_test_51KRSa9SBsGsaYp6jRDV3mfVAF2oyjXWHNmxbjvPRnXzWxB4tHfJGBVhNp9oqQjQrX2kVm8PBauuGXY4wXKCC3B2u00CMFEosMl');
var elements = stripe.elements();
var style = {
  base: {
    // Add your base input styles here. For example:
    fontSize: '16px',
    color: '#32325d',
  },
};

// Create an instance of the card Element.
var card = elements.create('card', {style: style});

// Add an instance of the card Element into the `card-element` <div>.
card.mount('#card-element');

var form = document.getElementById('payment-form');
form.addEventListener('submit', function(event) {
  event.preventDefault();

  stripe.createToken(card).then(function(result) {
    if (result.error) {
      // Inform the customer that there was an error.
      var errorElement = document.getElementById('card-errors');
      errorElement.textContent = result.error.message;
    } else {
      // Send the token to your server.
      stripeTokenHandler(result.token);
    }
  });
});

function stripeTokenHandler(token) {
  // Insert the token ID into the form so it gets submitted to the server
  var form = document.getElementById('payment-form');
  var hiddenInput = document.createElement('input');
  hiddenInput.setAttribute('type', 'hidden');
  hiddenInput.setAttribute('name', 'stripeToken');
  hiddenInput.setAttribute('value', token.id);
  form.appendChild(hiddenInput);

  // Submit the form
  form.submit();
}
</script> -->