config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  resources :checkouts
  
  get 'pages/home'
  get 'messages/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :charges, only: [:new, :create]
  resources :line_items
  resources :carts
  resources :instruments
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  root 'instruments#index'

  post 'messages', to: 'messages#create'

  get '/search' => 'instruments#search', :as => 'search_page'


  
  #resources :contactings, only: [:index, :new, :create] 
 
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/checkout.rb
class Checkout < ApplicationRecord
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  before_action :set_checkout, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  
  def index
    @checkouts = Checkout.all
  end

  def show
  end
  
  def new
    @checkout = Checkout.new
  end

  def edit
  end

  def create
    @checkout = Checkout.new(checkout_params)
    if @checkout.save
      redirect_to @checkout, notice: "Your Order was successfully created"    
    else
      render :new, status: :unprocessable_entity 
    end
  end
  
  def update
    if @checkout.update(checkout_params)
      redirect_to @checkout, notice: "Your Order was successfully updated." 
    else
      render :edit, status: :unprocessable_entity      
    end
  end

  def destroy
    @checkout.destroy
    redirect_to checkouts_path, notice: "Your Order was successfully destroyed." 
  end

  private  
  def set_checkout
    @checkout = Checkout.find(params[:id])
  end

  def checkout_params
    params.require(:checkout).permit(:firstname, :lastname, :email, :contact, :address1, :address2, :city, :state, :pincode)
  end
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/views/checkouts/_form.html.erb
<%= simple_form_for(@checkout) do |f| %>
<%= f.error_notification %>
<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>


<section class="section">
  <%= render(@cart.line_items) %>
  <div class="column total has-text-right">
   <h4 class="title is-4">
     <span class="f5 has-text-grey">Total:</span> <%= number_to_currency(@cart.total_price) %>
   </h4>
 </div>
</section>

<%#<%= button_to 'Return TO HomePage', @cart, method: :delete, data: { confirm: "Are you sure? " }, class: "btn" %>


<div class="form-inputs py-2 ">
  <h1>Enter details for Shipping Order</h1>
  <div class="field">
    <%= f.label :firstname %><br />
    <%= f.text_field :firstname, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.input_field :email, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :contact %><br />
    <%= f.input_field :contact, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :address1 %><br />
    <%= f.input_field :address1, autofocus: true%>
  </div>
  <div class="field">
    <%= f.label :address2 %><br />
    <%= f.input_field :address2, autofocus: true%>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.input_field :city, autofocus: true%>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.input_field :state, autofocus: true%>
  </div>
  <div class="field">
    <%= f.label :pincode %><br />
    <%= f.input_field :pincode, autofocus: true%>
  </div>

</div>

<div class="form-actions">
  <%= f.button :submit %>
 <%#  <%= button_to 'Empty Cart', @cart, method: :delete, data: { confirm: "Are you sure? " }, class: "button is-danger" %> 
</div>
<% end %>

app/views/checkouts/edit.html.erb
<h1>Editing Checkout</h1>

<%= render 'form', checkout: @checkout %>

<%= link_to 'Show', @checkout %> |
<%= link_to 'Back', checkouts_path %>

app/views/checkouts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Checkouts</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Contact</th>
      <th>Address1</th>
      <th>Address2</th>
      <th>City</th>
      <th>State</th>
      <th>Pincode</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @checkouts.each do |checkout| %>
    <tr>
      <td><%= checkout.firstname %></td>
      <td><%= checkout.lastname %></td>
      <td><%= checkout.email %></td>
      <td><%= checkout.contact %></td>
      <td><%= checkout.address1 %></td>
      <td><%= checkout.address2 %></td>
      <td><%= checkout.city %></td>
      <td><%= checkout.state %></td>
      <td><%= checkout.pincode %></td>
      <td><%= link_to 'Show', checkout %></td>
      <td><%= link_to 'Edit', edit_checkout_path(checkout) %></td>
      <td><%= link_to 'Destroy', checkout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Checkout', new_checkout_path %>

app/views/checkouts/new.html.erb
<h1>Billing Confirmation</h1>

<%= render 'form', checkout: @checkout %>

<%= link_to 'Back', checkouts_path %>

app/views/checkouts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container mt-5 mb-5">
  <div class="row d-flex justify-content-center">
   <div class="col-md-8">
    <div class="card">
      <div class="text-left logo p-2 px-5"> 
        <img src="https://i.imgur.com/2zDU056.png" width="50"> 
      </div>
      <div class="invoice p-5">
        <h5>Your order Confirmed!</h5> 
        <span class="font-weight-bold d-block mt-4">Dear Customer,</span> <span>You order has been confirmed and will be shipped in next two days!</span>
        <div class="payment border-top mt-3 mb-3 border-bottom table-responsive">
         <table class="table table-borderless">
          <tbody>
            <tr>
        <!-- <td>
        <div class="py-2"> <span class="d-block text-muted">Order Date</span> <span>   <%#<% Date.today %></span> </div>
      </td> -->
      <td>
        <div class="py-2"> <span class="d-block text-muted">Customer Name</span> <span><%= @checkout.firstname %>
        </span><span><%= @checkout.lastname %></span> </div>
      </td>
      <td>
        <div class="py-2"> <span class="d-block text-muted">Customer Email</span> <span><%= @checkout.email %>
        </span></div>
      </td>
      <td>
        <div class="py-2"> <span class="d-block text-muted">Contact</span> <span><%= @checkout.contact %></span> 
        </div>
      </td>
      <td>
        <div class="py-2"> <span class="d-block text-muted">Shiping Address</span> <span><%= @checkout.address1 %></span><span><%= @checkout.address2 %></span></div>
      </td>
    </tr>
  </tbody>
</table>
</div>
<div class="product border-bottom table-responsive">
  <table class="table table-borderless">
    <tbody>

      <section class="section">
        <%= render(@cart.line_items) %>
        <div class="column total has-text-right">
          <h4 class="title is-4">
            <span class="f5 has-text-grey">Total:</span> <%= number_to_currency(@cart.total_price) %>
          </h4>
        </div>
      </section>

    </tbody>
  </table>
</div>

<p>We will be sending shipping confirmation email when the item shipped successfully!</p>
<p class="font-weight-bold mb-0">Thanks for shopping with us!</p> <span>EMusic Team</span>
</div>
<div class="d-flex justify-content-between footer p-3"> <span>Need Help? visit our <span>support@emusic.com</span> help center</a></span> </div>
</div>
</div>
</div>
</div> 

<%#<%= link_to 'Edit', edit_checkout_path(@checkout) %> 
<%#<%= link_to 'Back', checkouts_path %>