config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  resources :checkouts
  
  get 'pages/home'
  get 'messages/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :charges, only: [:new, :create]
  resources :line_items
  resources :carts
  resources :instruments
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  root 'instruments#index'

  post 'messages', to: 'messages#create'

  get '/search' => 'instruments#search', :as => 'search_page'


  
  #resources :contactings, only: [:index, :new, :create] 
 
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :instrument
  belongs_to :cart

  def total_price
    instrument.price.to_i * quantity.to_i
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_line_item, only: %i[ show edit update destroy ]
  before_action :set_cart, only: [:create]
  before_action :authenticate_user!

  def index
    @line_items = LineItem.all
  end

  def show
  end

  def new
    @line_item = LineItem.new
  end

  def edit
  end

  def create
    instrument = Instrument.find(params[:instrument_id])
    @line_item = @cart.add_instrument(instrument)
    if @line_item.save
      redirect_to @line_item.cart, notice: "Item Added to cart" 
    else
      render :new, status: :unprocessable_entity 
    end
  end

  def update
    if @line_item.update(line_item_params)
      redirect_to @line_item, notice: "Item was successfully updated." 
    else
      render :edit, status: :unprocessable_entity 
    end
  end

  def destroy
    @cart = Cart.find(session[:cart_id])
    @line_item.destroy
    redirect_to cart_path, notice: "Item was successfully destroyed." 
  end

  private

  def set_line_item
    @line_item = LineItem.find(params[:id])
  end

  def line_item_params
    params.require(:line_item).permit(:instrument_id)
  end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= simple_form_for(@line_item) do |f| %>
<%= f.error_notification %>
<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<div class="form-inputs">
  <%= f.association :instrument %>
  <%= f.association :cart %>
</div>

<div class="form-actions">
  <%= f.button :submit %>
</div>
<% end %>

app/views/line_items/_line_item.html.erb
<div class="columns align-items-center">
  <div class="column is-1">
    <%= line_item.quantity %>
  </div>
  <div class="column is-2">
    <figure class="is-128x128 image">
      <%= image_tag(line_item.instrument.image) %>
    </figure>
  </div>
  <div class="column is-9">
    <strong><%= line_item.instrument.title %></strong>
    <div class="columns align-items-center">
      <div class="content column is-9">
        <%= truncate(line_item.instrument.description, length: 140) %>
      </div>
      <div class="column is-3 has-text-right">
        <strong class="f4"><%= number_to_currency(line_item.total_price) %></strong>
      </div>
    </div>
  </div>
</div>

<div class="has-text-right">
  <%= link_to 'Remove Item', line_item, method: :delete, data: { confirm: "Are you sure? " }, class: "button is-small mb4" %>
</div>

<hr/ >

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Instrument</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
    <tr>
      <td><%= line_item.instrument %></td>
      <td><%= line_item.cart %></td>
      <td><%= link_to 'Show', line_item %></td>
      <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
      <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line Item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Instrument:</strong>
  <%= @line_item.instrument %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>