config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  resources :checkouts
  
  get 'pages/home'
  get 'messages/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :charges, only: [:new, :create]
  resources :line_items
  resources :carts
  resources :instruments
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  root 'instruments#index'

  post 'messages', to: 'messages#create'

  get '/search' => 'instruments#search', :as => 'search_page'


  
  #resources :contactings, only: [:index, :new, :create] 
 
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/instrument.rb
class Instrument < ApplicationRecord
	has_one_attached :image
	has_many :line_items
	belongs_to :user
	
	serialize :image, JSON
	
	before_destroy :not_referenced_by_any_line_item

	validates :title, :brand, :price, :model, presence: true
	validates :description, length: { maximum: 1000, too_long: "%{count} characters is the maximum allowed "}
	validates :title, length: {maximum: 140, too_long: "%{count} characters is the maximum allowed"}
	validates :price, numericality: {only_integer: true}, length: {maximum: 7}

  BRAND = %w{ Fender Gibson Epiphone ESP Martin Dean Taylor Jackson PRS  Ibanez Charvel Washburn }
  FINISH = %w{ Black White Navy Blue Red Clear Satin Yellow Seafoam }
  CONDITION = %w{ New Excellent Mint Used Fair Poor }

  # def to_s
  # 	title
  # end

  private

  def not_referenced_by_any_line_item
  	unless line_items.empty?
  		errors.add(:base, "Line items present")
  		throw :abort
  	end
  end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_action :set_instrument, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @instruments = Instrument.all.order("created_at desc")
  end

  def show
  end

  # def search
  #   if params[:search].blank?
  #     redirect_to(instruments_path, alert: "Empty field!") and return
  #   else
  #    keyword = params[:search]
  #    @instruments = Instrument.where("lower(title) LIKE ?", "%#{keyword}%")
  #   end
  # end
  
  def search
    if params[:search].blank?
      redirect_to(instruments_path, alert: "Empty field!") and return
    else
      @instruments = Instrument.where("lower(title) LIKE ?", "#{params[:search]}%" )
    end
  end

  def new
    @instrument = current_user.instruments.build
  end

  def edit
    @instrument = current_user.instruments.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to intruments_path, notice: "You cannot edit this instrument."
  end

  def create
    @instrument = current_user.instruments.build(instrument_params)

    # token = params[:stripeToken]
    # instrument_brand = params[:brand]
    # instrument_title = params[:title]
    # #error
    # card_brand = params[:user][:card_brand]
    # card_exp_month = params[:user][:card_exp_month]
    # card_exp_year = params[:user][:card_exp_year]
    # card_last4 = params[:user][:card_last4]

    # charge = Stripe::Charge.create(
    #   :amount => 30000,
    #   :currency => "inr",
    #   :description => instrument_brand,
    #   :statement_descriptor => instrument_title,
    #   :source => token
    # )
    # current_user.stripe_id = charge.id
    # current_user.card_brand = card_brand
    # current_user.card_exp_month = card_exp_month
    # current_user.card_exp_year = card_exp_year
    # current_user.card_last4 = card_last4
    # current_user.save!

    if @instrument.save
      InstrumentMailer.with(user: current_user, instrument: @instrument).instrument_created.deliver_later
      redirect_to @instrument, notice: "Instrument was created successfully." 
    else
      render 'new'
    end

  # rescue Stripe::CardError => e
  #   flash.alert = e.message
  #   render action: :new  
  end

  def update
    if @instrument.update(instrument_params)
      redirect_to @instrument, notice: "Instrument was updated successfully." 
    else
      render 'edit'
    end
  end
  
  def destroy
    @instrument.destroy
    redirect_to instruments_path, notice: "Instrument was destroy successfully."   
  end

  private
  def set_instrument
    @instrument = Instrument.find(params[:id])
  end

  def instrument_params
    params.require(:instrument).permit(:brand, :model, :description, :condition, :finish, :title, :price, :image)
  end
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
	def instrument_author(instrument)
      user_signed_in? && current_user.id == instrument.user_id
  end
end

app/views/instruments/_form.html.erb
<div class="columns">
  <div class="column is-8 is-centered">

    <%= simple_form_for @instrument, html: { multipart: true } do |f| %>
    <%= f.error_notification %>

    <div class="columns">

      <div class="field column is-9">
        <div class="control">
          <%= f.input :title , required: true, input_html: { class: "input"}, wrapper: false, label_html: { class:"label" } %>
        </div>
      </div>

      <div class="field column">
        <div class="control">
          <%= f.input :price, required: true, input_html: { class:"input", maxlength: 7  }, wrapper: false, label_html: { class:"label" } %>
        </div>
      </div>

    </div>

    <div class="field">
      <div class="control">
        <%= f.input :model, required: true, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" } %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= f.input :description, required: true, input_html: { class:"textarea" }, wrapper: false, label_html: { class:"label" } %>
      </div>
    </div>

    <div class="columns">
      <div class="field column is-4">
        <div class="control">
          <label class="label">Brand</label>
          <div class="control has-icons-left">
            <span class="select">
              <%= f.input_field :brand, collection: Instrument::BRAND, prompt: "Select brand" %>
            </span>
            <span class="icon is-small is-left">
              <i class="fa fa-tag"></i>
            </span>
          </div>
        </div>
      </div>

      <div class="field column is-4">
        <div class="control">
          <label class="label">Finish</label>
          <div class="control has-icons-left">
            <span class="select">
              <%= f.input_field :finish, collection: Instrument::FINISH, prompt: "Select finish" %>
            </span>
            <span class="icon is-small is-left">
              <i class="fa fa-paint-brush"></i>
            </span>
          </div>
        </div>
      </div>

      <div class="field column is-4">
        <div class="control">
          <label class="label">Condition</label>
          <div class="control has-icons-left">
            <span class="select">
              <%= f.input_field :condition, collection: Instrument::CONDITION, prompt: "Select condition" %>
            </span>
            <span class="icon is-small is-left">
              <i class="fa fa-paint-brush"></i>
            </span>
          </div>
        </div>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <label class="label">Add images</label>
        <div class="file">
          <label class="file-label">
            <%= f.input :image, as: :file, input_html: { class:"file-input instrument-image" }, label: false, wrapper: false %>
            <span class="file-cta">
              <span class="file-icon"><i class="fa fa-upload"></i></span>
              <span class="file-label">Choose a file…</span>
            </span>
          </label>
        </div>
      </div>
    </div>
    <output id="list"></output>
    <hr />

    <div class="field is-grouped">
      <div class="control">
        <%= f.button :submit, class: 'button is-warning' %>
        <%= link_to 'Cancel', instruments_path, class:'button is-light' %>
      </div>
    </div>

    <% end %>
  </div>
</div>

app/views/instruments/_payment.html.erb
<section class="section">
  <h4 class="subtitle is-4">Payment</h4>

  <div class="notification is-light has-text-centered">
  	<i class="fa fa-credit-card"></i>
  	All Instrument Cost <strong>$300</strong> USD
  	<span class="blocl mb4"></span>
  </div>

  <div class="form-row">
  	<label for="card-element" class="label">
  		Enter credit or debit card
  	</label>

  	<div id="card-element" class="form-control">
  		<!-- stripe element inserted -->
  	</div>
    <!-- display error -->
    <div id="card-errors" role="alert"></div>
  </div>
  
  <% if current_user.stripe_id.present? %>
  <div class="last-card bg-light pa4 border-radius-3 mt4">
    <h5 class="is-6 title pt2">Previously used card</h5>
    <table class="table is-narrow bg-light is-fullwidth">
     <thead>
      <th>Card Brand</th>
      <th>Last 4 Digits </th>
      <th>Expiration Month</th>
      <th>Expiration Year</th>
    </thead>
    <tr>
      <td><%= current_user.card_brand %></td>
      <td><%= current_user.card_last4 %></td>
      <td><%= current_user.card_exp_month %></td>
      <td><%= current_user.card_exp_year %></td>
    </tr>
  </table>
</div>
<% end %>
</section>
 

app/views/instruments/edit.html.erb
<% content_for :header do %>
<section class="hero is-info">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Editing Instrument
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', instrument: @instrument %>
</div>

app/views/instruments/index.html.erb
<% content_for :header do %>

<!-- <div>
 <%# <%= render 'payment' %>
</div> 
-->

<section class="hero is-info">
  <div class="hero-body">
    <div class="container">
      <h5>Welcome to Our Emusic Shop</h5>
      <h1 class="title">
        Browse the latest instruments on EMusic Shop
      </h1>
    </div>
  </div>
</section>
<% end %>

<!doctype html>
  <html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    

  </head>
  <body>

    <!-- collection -->
    <section id = "collection" class = "py-2">
      <div class = "container">
        <div class = "title text-center">
          <h2 class = "position-relative d-inline-block">New Collection</h2>
        </div>
      </div>
    </section>

  </body>
  </html>

  <div class="instrument-index-grid pt4">
    <% @instruments.each do |instrument| %> 
    <div class="instrument border-light">
      <div class="instrument-thumb">

        <%= image_tag instrument.image if instrument.image.attached? %>

        <%#  <%= link_to image_tag(instrument.image_url(:thumb)), instrument %>
        
        <% if instrument.condition? %>
        <div class="condition">
          <span class="tag is-dark"><%= instrument.condition %></span>
        </div>
        <% end %>
      </div>

      <div class="pa3">

        <h3 class="fw7 f4 title"><%= link_to instrument.title, instrument %></h3>

        <p class="has-text-gray fg pt1">Sold by <%= instrument.user.name %></p>

        <p class="f3 fw6 has-text-right pt2 price"><%= number_to_currency(instrument.price) %></p>

        <% if instrument_author(instrument) %>
        <%= link_to 'Edit', edit_instrument_path(instrument), class: "button is-small" %>
        <%= link_to 'Delete', instrument, method: :delete, data: { confirm: "Are you sure ?" }, class: "button is-small" %>
        <% end %>

      </div>
    </div>
    <% end %>
</div>

app/views/instruments/new.html.erb
<% content_for :header do %>
<section class="hero is-info">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Adding an Instrument
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', instrument: @instrument %>
</div>

app/views/instruments/search.html.erb
<body class="container" style="background: #f2f2f2"> 
  <h1 class="my-3" style="color: #6699ff;"><b>Searching result</b></h1>
  <div name="instruments">
   <div class = "row">
    <% @instruments.each do |instrument| %>
    <div class = "col-md-3">
    <div class="card" style="width: 18rem;">
     <%= image_tag instrument.image if instrument.image.attached? %>
     <div class="card-body">
       <h5 class="card-title"><%= link_to instrument.title, @instrument_path %></h5>                     

       <p><b><%= instrument.price %>$</b></p>
       
     </div>
   </div>
 </div>
   <% end %>

 </div>
</body>

app/views/instruments/show.html.erb
<% content_for :body_class, 'bg-light' %>

<section class="section instrument-show">
  <div class="columns">
    <div class="column is-8">
      <h1 class="title is-2"><%= @instrument.title%></h1>

      <ul class="pv1">
        <% if @instrument.brand? %>
        <li class="inline-block pr3"><%= @instrument.brand %></li>
        <% end %>

        <li class="inline-block pr3"><%= @instrument.model %></li>

        <% if @instrument.condition? %>
        <li class="inline-block pr3"><%= @instrument.condition %></li>
        <% end %>
      </ul>

     <!--  <div class="feature-image">
   <%#    <%= image_tag(@instrument.image_url(:default)) %>
 </div> -->
 <div class="feature-image">
   <%= image_tag(@instrument.image) if @instrument.image.attached? %>
 </div>


 <div class="content pa4 mt3 bg-white border-radius-3">

  <h3 class="subtitle is-4">Description</h3>
  <%= @instrument.description %>


  <h3 class="subtitle is-4 pt5">Product Specs</h3>

  <table class="table is-narrow">
    <% if @instrument.condition %>
    <tr>
      <td class="has-text-weight-bold">Condition:</td>
      <td><%= @instrument.condition %></td>
    </tr>
    <% end %>
    <% if @instrument.finish %>
    <tr>
      <td class="has-text-weight-bold">Finish:</td>
      <td><%= @instrument.finish %></td>
    </tr>
    <% end %>
    <% if @instrument.brand %>
    <tr>
      <td class="has-text-weight-bold">Brand:</td>
      <td><%= @instrument.brand %></td>
    </tr>
    <% end %>

    <tr>
      <td class="has-text-weight-bold">Model:</td>
      <td><%= @instrument.model %></td>
    </tr>
  </table>
</div>
</div>
<div class="column is-3 is-offset-1">
 <div class="bg-white pa4 border-radius-3">
  <h4 class="title is-5 has-text-centered"><%= number_to_currency(@instrument.price) %></h4>
  <p class="has-text-centered mb4">Sold by <%= @instrument.user.name %></p>
  <%= button_to 'Add to cart', line_items_path(instrument_id: @instrument), class: 'button is-warning add-to-cart' %>
</div> 
</div>
</div>

<% if instrument_author(@instrument) %>
<%= link_to 'Edit', edit_instrument_path(@instrument), class: 'button' %>
<% end %>
</section>